id = "vscode-dark-modern-2024"
name = "VSCodeDarkModern2024"
version = "0.0.5"
schema_version = 1
authors = ["kcamcam <kevincamellini@gmail.com>"]
description = "VSCode Dark Modern Theme for Zed"
repository = "https://github.com/kcamcam/vscode_dark_modern.zed"
