id = "vscode-dark-modern-2"
name = "VSCode Dark Modern 2"
version = "0.0.6"
schema_version = 1
authors = ["kcamcam <kevincamellini@gmail.com>"]
description = "VSCode Dark Modern Theme for Zed"
repository = "https://github.com/kcamcam/vscode_dark_modern.zed"
